Gorodetskiy_Konstantin_dz4/about_me/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.views.generic import TemplateView
from my_profile.views import MyProfileView, MyStudyView, MyWorkView, OrganizationDetailsView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='main_page'),
    url(r'^about-me/$', MyProfileView.as_view(), name='about_me'),
    url(r'^study/$', MyStudyView.as_view(), name='study'),
    url(r'^work/$', MyWorkView.as_view(), name='work'),
    url(r'^organization/(?P<pk>[0-9]+)/$', OrganizationDetailsView.as_view(), name='organization'),

]

Gorodetskiy_Konstantin_dz4/my_profile/models.py
from django.db import models


class Hobby(models.Model):
    name = models.CharField('Хобби', max_length=30, blank=False)
    icon = models.CharField('Иконка', max_length=30, blank=False)

    def __str__(self):
        return self.name


class Organization(models.Model):
    name = models.CharField('Организация', max_length=100, blank=False)
    logo_file = models.CharField('Логотип', max_length=30, blank=False)
    logo_width = models.CharField('Ширина логотипа', max_length=10, default='200px', blank=False)
    organization_url = models.URLField('Ссылка на сайт', max_length=100, blank=False)
    city = models.CharField('Город', max_length=100)
    address = models.CharField('Адрес', max_length=150)
    phone = models.CharField('Телефон', max_length=100)

    def __str__(self):
        return self.name


class Study(models.Model):
    school = models.ForeignKey(Organization, verbose_name='Учебное заведение', related_name='studies')
    specialization = models.CharField('Специализация', max_length=100, blank=False)
    certificate_url = models.URLField('Ссылка на сертификат', max_length=200, blank=True)

    def __str__(self):
        return self.school.name


class Work(models.Model):
    company = models.ForeignKey(Organization, verbose_name='Компания', related_name='works')
    specialization = models.CharField('Должность', max_length=100, blank=False)

    def __str__(self):
        return self.company.name

Gorodetskiy_Konstantin_dz4/my_profile/views.py
from django.views.generic import ListView, DetailView
from .models import Hobby, Study, Work, Organization
import datetime


class MyProfileView(ListView):
    model = Hobby
    template_name = 'about_me.html'

    def get_context_data(self, **kwargs):
        context = super(MyProfileView, self).get_context_data(**kwargs)
        context['my_name'] = 'Городецкий Константин'
        context['birth_date'] = datetime.date(1982, 8, 28)
        return context


class MyStudyView(ListView):
    model = Study


class MyWorkView(ListView):
    model = Work

class OrganizationDetailsView(DetailView):
    model = Organization

Gorodetskiy_Konstantin_dz4/templates/about_me.html
{% extends "base.html" %}
{% load static %}

{% block title %}Обо мне{% endblock %}
{% block page_header %}Обо мне{% endblock %}

{% block content %}

<div class="row">
  <div class="col-md-7">
    <img src="{% static "img/me.jpg" %}" class="img-thumbnail">
  </div>
  <div class="col-md-5">
    <div class="jumbotron">
      <h3>
        {{ my_name }}, {{ birth_date|date:'Y' }}
      </h3>
      <table class='table'>
      {% for hobby in object_list %}
        <tr>
          <td>
            <i class="fa {{ hobby.icon }} fa-3x" aria-hidden="true"></i>
          </td>
          <td style="vertical-align: middle;">
            {{ hobby.name }}
          </td>
        </tr>
      {% endfor %}
      </table>
    </div>
  </div>
</div>

{% endblock %}

Gorodetskiy_Konstantin_dz4/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Домашнее задание №3{% endblock %}</title>

    <link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
    <link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous">
    <link
      href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css"
      rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    {% include 'navbar.html' %}
    <div class="container">
      <div class="page-header">
        <h1>{% block page_header %}{% endblock %}</h1>
      </div>
      {% block content %}{% endblock %}
    </div>

    <script
      src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
    </script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous">
    </script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="https://use.fontawesome.com/adc5384346.js"></script>
    <script src="{% static "js/scripts.js" %}"></script>
  </body>
</html>

Gorodetskiy_Konstantin_dz4/templates/index.html
{% extends "base.html" %}

{% block page_header %}Домашнее задание №4{% endblock %}

{% block content %}

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <td>
      1. В своей копии проекта отделить модель Организации, добавив еще
      пару-тройку полей (например, адрес и номер телефона). Пересоздать БД
      заново, и наполнить её информацией, используя скрипт.
    </td>
  </tr>
  <tr>
    <td class="success">
      <ul>
        <li>Модель Organization была создана в ДЗ №3</li>
        <li>Добавил поля city, address, phone</li>
        {% include 'snippets/models.html' %}
        <li>Пересоздал БД</li>
        <li>Наполнил информацией</li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>
      2. На странице отображения мест работы, имена организаций сделать в виде
      гиперссылок, при переходе по которым должна показываться карточка данной
      организации с полной информацией об организации. Не забудте сделать
      отдельный шаблон, для отображения информации об организации. <br />
      P.S. Чтобы реализовать правильные url-адреса для организаций почитайте
      этот раздел djangobook.
    </td>
  </tr>
  <tr>
    <td class="success">
      <ul>
        <li>
          На странице <a href="{% url 'work' %}">Работа</a> поправил ссылки:
          теперь при нажатии на логотип просходит переход на официальный сайт
          организации, а при нажатии на название - переход на карточку организации
          {% include 'snippets/work_list.html' %}
        </li>
        <li>
          Добавил карточки организаций
          {% include 'snippets/organization.html' %}
        </li>
        <li>
          Для перехода к карточке организации подготовил соответсвующий url-шаблон
          {% include 'snippets/url.html' %}
        </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>
      3. * (усложненное) На странице «Работа» добавьте флаг(check-box), который
      позволит отбражать только последние три места работы. Если у вас три или
      меньше места работы, добавьте несколько произвольных мест для проверки
      данного фильтра.
    </td>
    </tr>
    <tr>
      <td class="success">
        <ul>
          <li>
            На странице <a href="{% url 'work' %}">Работа</a> добавил переключатель
            {% include 'snippets/switcher.html' %}
          </li>
          <li>
            Добавил js-обработчик в js/scripts.js
            {% include 'snippets/js.html' %}
          </li>
        </ul>
      </td>
    </tr>
</table>

{% endblock %}

Gorodetskiy_Konstantin_dz4/templates/my_profile/organization_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{object.name}}{% endblock %}
{% block page_header %}{{object.name}}{% endblock %}

{% block content %}

<center>
    <a href="{{ object.organization_url }}" target="_blank">
      <img src="{% static "img/" %}{{ object.logo_file }}" width="{{ object.logo_width }}">
    </a>
    <a href="{% url 'organization' object.id %}">
      <h4>{{ object.company }}</h4>
    </a>
    <p>{{ object.city }}, {{ object.address }}</p>
    <p>{{ object.phone }}</p>

</center>

{% endblock %}

Gorodetskiy_Konstantin_dz4/templates/my_profile/study_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Учеба{% endblock %}
{% block page_header %}Учеба{% endblock %}

{% block content %}

<center>
  {% for study in object_list %}
    <a href="{{ study.school.organization_url }}" target="_blank">
      <img src="{% static "img/" %}{{ study.school.logo_file }}" width="{{ study.school.logo_width }}" />
    <h4>{{ study.school }}</h4>
    </a>
    {% if study.certificate_url %}
      <a href="{{ study.certificate_url }}" target="_blank">
        <p>{{ study.specialization }}</p>
      </a>
    {% else %}
      <p>{{ study.specialization }}</p>
    {% endif %}
    <hr />
  {% endfor %}
</center>

{% endblock %}

Gorodetskiy_Konstantin_dz4/templates/my_profile/work_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Работа{% endblock %}
{% block page_header %}Работа{% endblock %}

{% block content %}

<center>

  <label class="checkbox-inline">
    <input class="show_works" type="checkbox" checked data-toggle="toggle"  data-off="3 последних<br />места" data-on="Все<br />места">
  </label>
  
  <hr />
  {% for work in object_list %}
    <div class="work">
      <a href="{{ work.company.organization_url }}" target="_blank">
        <img src="{% static "img/" %}{{ work.company.logo_file }}" width="{{ work.company.logo_width }}">
      </a>
      <a href="{% url 'organization' work.company.id %}">
        <h4>{{ work.company }}</h4>
      </a>
      <p>{{ work.specialization }}</p>
    <hr />
    </div>
  {% endfor %}
</center>

{% endblock %}

Gorodetskiy_Konstantin_dz4/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button
        type="button"
        class="navbar-toggle collapsed"
        data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1"
        aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ДЗ 4</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        {% with request.resolver_match.url_name as url_name %}
        <li
          {% if url_name == 'main_page' %}
            class="active"
          {% endif %}>
          <a href="{% url 'main_page' %}">Главная</a>
        </li>
        <li
          {% if url_name == 'about_me' %}
            class="active"
          {% endif %}>
          <a href="{% url 'about_me' %}">Обо мне</a>
        </li>
        <li
          {% if url_name == 'study' %}
            class="active"
          {% endif %}>
          <a href="{% url 'study' %}">Учеба</a>
        </li>
        <li
          {% if url_name == 'work' %}
            class="active"
          {% endif %}>
          <a href="{% url 'work' %}">Работа</a>
        </li>
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>

Gorodetskiy_Konstantin_dz4/templates/snippets/js.html
<pre style='background: none; border: none;'>
  $<span style='color:#808030; '>(</span> <span style='color:#800000; '>"</span><span style='color:#0000e6; '>.show_works</span><span style='color:#800000; '>"</span> <span style='color:#808030; '>)</span><span style='color:#808030; '>.</span>change<span style='color:#808030; '>(</span><span style='color:#800000; font-weight:bold; '>function</span><span style='color:#808030; '>(</span><span style='color:#808030; '>)</span> <span style='color:#800080; '>{</span>
    <span style='color:#800000; font-weight:bold; '>if</span><span style='color:#808030; '>(</span>$<span style='color:#808030; '>(</span><span style='color:#800000; '>'</span><span style='color:#0000e6; '>.show_works</span><span style='color:#800000; '>'</span><span style='color:#808030; '>)</span><span style='color:#808030; '>.</span>is<span style='color:#808030; '>(</span><span style='color:#800000; '>"</span><span style='color:#0000e6; '>:checked</span><span style='color:#800000; '>"</span><span style='color:#808030; '>)</span><span style='color:#808030; '>)</span>
      $<span style='color:#808030; '>(</span> <span style='color:#800000; '>"</span><span style='color:#0000e6; '>.work:gt(2)</span><span style='color:#800000; '>"</span> <span style='color:#808030; '>)</span><span style='color:#808030; '>.</span>show<span style='color:#808030; '>(</span><span style='color:#800000; '>"</span><span style='color:#0000e6; '>slow</span><span style='color:#800000; '>"</span><span style='color:#808030; '>,</span> <span style='color:#800000; font-weight:bold; '>function</span><span style='color:#808030; '>(</span><span style='color:#808030; '>)</span> <span style='color:#800080; '>{</span>
      <span style='color:#800080; '>}</span><span style='color:#808030; '>)</span><span style='color:#800080; '>;</span>
  <span style='color:#800000; font-weight:bold; '>else</span>
      $<span style='color:#808030; '>(</span> <span style='color:#800000; '>"</span><span style='color:#0000e6; '>.work:gt(2)</span><span style='color:#800000; '>"</span> <span style='color:#808030; '>)</span><span style='color:#808030; '>.</span>hide<span style='color:#808030; '>(</span><span style='color:#800000; '>"</span><span style='color:#0000e6; '>slow</span><span style='color:#800000; '>"</span><span style='color:#808030; '>,</span> <span style='color:#800000; font-weight:bold; '>function</span><span style='color:#808030; '>(</span><span style='color:#808030; '>)</span> <span style='color:#800080; '>{</span>
      <span style='color:#800080; '>}</span><span style='color:#808030; '>)</span><span style='color:#800080; '>;</span>
  <span style='color:#800080; '>}</span><span style='color:#808030; '>)</span><span style='color:#800080; '>;</span>

</pre>

Gorodetskiy_Konstantin_dz4/templates/snippets/models.html
<pre style='background: none; border: none;'>
  <span style='color:#800000; font-weight:bold; '>class</span> Organization<span style='color:#808030; '>(</span>models<span style='color:#808030; '>.</span>Model<span style='color:#808030; '>)</span><span style='color:#808030; '>:</span>
    name <span style='color:#808030; '>=</span> models<span style='color:#808030; '>.</span>CharField<span style='color:#808030; '>(</span><span style='color:#0000e6; '>'Организация'</span><span style='color:#808030; '>,</span> max_length<span style='color:#808030; '>=</span><span style='color:#008c00; '>100</span><span style='color:#808030; '>,</span> blank<span style='color:#808030; '>=</span><span style='color:#074726; '>False</span><span style='color:#808030; '>)</span>
    logo_file <span style='color:#808030; '>=</span> models<span style='color:#808030; '>.</span>CharField<span style='color:#808030; '>(</span><span style='color:#0000e6; '>'Логотип'</span><span style='color:#808030; '>,</span> max_length<span style='color:#808030; '>=</span><span style='color:#008c00; '>30</span><span style='color:#808030; '>,</span> blank<span style='color:#808030; '>=</span><span style='color:#074726; '>False</span><span style='color:#808030; '>)</span>
    logo_width <span style='color:#808030; '>=</span> models<span style='color:#808030; '>.</span>CharField<span style='color:#808030; '>(</span><span style='color:#0000e6; '>'Ширина логотипа'</span><span style='color:#808030; '>,</span> max_length<span style='color:#808030; '>=</span><span style='color:#008c00; '>10</span><span style='color:#808030; '>,</span> default<span style='color:#808030; '>=</span><span style='color:#0000e6; '>'200px'</span><span style='color:#808030; '>,</span> blank<span style='color:#808030; '>=</span><span style='color:#074726; '>False</span><span style='color:#808030; '>)</span>
    organization_url <span style='color:#808030; '>=</span> models<span style='color:#808030; '>.</span>URLField<span style='color:#808030; '>(</span><span style='color:#0000e6; '>'Ссылка на сайт'</span><span style='color:#808030; '>,</span> max_length<span style='color:#808030; '>=</span><span style='color:#008c00; '>100</span><span style='color:#808030; '>,</span> blank<span style='color:#808030; '>=</span><span style='color:#074726; '>False</span><span style='color:#808030; '>)</span>
    <b><u>city</u></b> <span style='color:#808030; '>=</span> models<span style='color:#808030; '>.</span>CharField<span style='color:#808030; '>(</span><span style='color:#0000e6; '>'Город'</span><span style='color:#808030; '>,</span> max_length<span style='color:#808030; '>=</span><span style='color:#008c00; '>100</span><span style='color:#808030; '>)</span>
    <b><u>address</u></b> <span style='color:#808030; '>=</span> models<span style='color:#808030; '>.</span>CharField<span style='color:#808030; '>(</span><span style='color:#0000e6; '>'Адрес'</span><span style='color:#808030; '>,</span> max_length<span style='color:#808030; '>=</span><span style='color:#008c00; '>150</span><span style='color:#808030; '>)</span>
    <b><u>phone</u></b> <span style='color:#808030; '>=</span> models<span style='color:#808030; '>.</span>CharField<span style='color:#808030; '>(</span><span style='color:#0000e6; '>'Телефон'</span><span style='color:#808030; '>,</span> max_length<span style='color:#808030; '>=</span><span style='color:#008c00; '>100</span><span style='color:#808030; '>)</span>

  <span style='color:#800000; font-weight:bold; '>def</span> <span style='color:#074726; '>__str__</span><span style='color:#808030; '>(</span>self<span style='color:#808030; '>)</span><span style='color:#808030; '>:</span>
    <span style='color:#800000; font-weight:bold; '>return</span> self<span style='color:#808030; '>.</span>name
</pre>

Gorodetskiy_Konstantin_dz4/templates/snippets/organization.html
{% verbatim %}
<pre style='background: none; border: none;'>{% extends "base<span style='color:#008c00; '>.</span>html" %}
{% load static %}

{% block title %}{{object<span style='color:#008c00; '>.</span>name}}{% endblock %}
{% block page_header %}{{object<span style='color:#008c00; '>.</span>name}}{% endblock %}

{% block content %}

<span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>center</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>a</span><span style='color:#274796; '> </span><span style='color:#074726; '>href</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"{{ object.organization_url }}"</span><span style='color:#274796; '> </span><span style='color:#074726; '>target</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"_blank"</span><span style='color:#a65700; '>></span>
      <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>img</span><span style='color:#274796; '> </span><span style='color:#074726; '>src</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"{% static "</span><span style='color:#274796; '>img/</span><span style='color:#0000e6; '>" %}{{ object.logo_file }}"</span><span style='color:#274796; '> </span><span style='color:#074726; '>width</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"{{ object.logo_width }}"</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>a</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>a</span><span style='color:#274796; '> </span><span style='color:#074726; '>href</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"{% url 'organization' object.id %}"</span><span style='color:#a65700; '>></span>
      <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>h4</span><span style='color:#a65700; '>></span>{{ object<span style='color:#008c00; '>.</span>company }}<span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>h4</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>a</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>p</span><span style='color:#a65700; '>></span>{{ object<span style='color:#008c00; '>.</span>city }}, {{ object<span style='color:#008c00; '>.</span>address }}<span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>p</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>p</span><span style='color:#a65700; '>></span>{{ object<span style='color:#008c00; '>.</span>phone }}<span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>p</span><span style='color:#a65700; '>></span>

<span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>center</span><span style='color:#a65700; '>></span>

{% endblock %}
</pre>
{% endverbatim %}

Gorodetskiy_Konstantin_dz4/templates/snippets/switcher.html
<pre style='background: none; border: none;'>
<span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>label</span><span style='color:#274796; '> </span><span style='color:#074726; '>class</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"checkbox-inline"</span><span style='color:#a65700; '>></span>
      <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>input</span><span style='color:#274796; '> </span><span style='color:#074726; '>class</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"show_works"</span><span style='color:#274796; '> </span><span style='color:#074726; '>type</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"checkbox"</span><span style='color:#274796; '> </span><span style='color:#074726; '>checked</span><span style='color:#274796; '> </span><span style='color:#074726; '>data</span><span style='color:#274796; '>-toggle</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"toggle"</span><span style='color:#274796; '>  </span><span style='color:#074726; '>data</span><span style='color:#274796; '>-off</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"3 последних&lt;br />места"</span><span style='color:#274796; '> </span><span style='color:#074726; '>data</span><span style='color:#274796; '>-on</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"Все&lt;br />места"</span><span style='color:#a65700; '>></span>
<span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>label</span><span style='color:#a65700; '>></span>
</pre>

Gorodetskiy_Konstantin_dz4/templates/snippets/url.html
{% verbatim %}
<pre style='background: none; border: none;'>url<span style='color:#808030; '>(</span><span style='color:#0000e6; '>r'^organization/(?P&lt;pk>[0-9]+)/$'</span><span style='color:#808030; '>,</span> OrganizationDetailsView<span style='color:#808030; '>.</span>as_view<span style='color:#808030; '>(</span><span style='color:#808030; '>)</span><span style='color:#808030; '>,</span> name<span style='color:#808030; '>=</span><span style='color:#0000e6; '>'organization'</span><span style='color:#808030; '>)</span>
</pre>
{% endverbatim %}

Gorodetskiy_Konstantin_dz4/templates/snippets/work_list.html
{% verbatim %}
<pre style='background: none; border: none;'><span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>center</span><span style='color:#a65700; '>></span>
  {% for work in object_list %}
    <b><u><span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>a</span><span style='color:#274796; '> </span><span style='color:#074726; '>href</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"{{ work.company.organization_url }}"</span><span style='color:#274796; '> </span><span style='color:#074726; '>target</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"_blank"</span><span style='color:#a65700; '>></span></u></b>
      <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>img</span><span style='color:#274796; '> </span><span style='color:#074726; '>src</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"{% static "</span><span style='color:#274796; '>img/</span><span style='color:#0000e6; '>" %}{{ work.company.logo_file }}"</span><span style='color:#274796; '> </span><span style='color:#074726; '>width</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"{{ work.company.logo_width }}"</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>a</span><span style='color:#a65700; '>></span>
    <b><u><span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>a</span><span style='color:#274796; '> </span><span style='color:#074726; '>href</span><span style='color:#808030; '>=</span><span style='color:#0000e6; '>"{% url 'organization' work.company.id %}"</span><span style='color:#a65700; '>></span></u></b>
      <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>h4</span><span style='color:#a65700; '>></span>{{ work<span style='color:#008c00; '>.</span>company }}<span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>h4</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>a</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>p</span><span style='color:#a65700; '>></span>{{ work<span style='color:#008c00; '>.</span>specialization }}<span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>p</span><span style='color:#a65700; '>></span>
    <span style='color:#a65700; '>&lt;</span><span style='color:#800000; font-weight:bold; '>hr</span><span style='color:#274796; '> </span><span style='color:#a65700; '>/></span>
  {% endfor %}
<span style='color:#a65700; '>&lt;/</span><span style='color:#800000; font-weight:bold; '>center</span><span style='color:#a65700; '>></span>
</pre>
{% endverbatim %}